/**
 * Store exports with namespacing to avoid conflicts
 */

// Editor store - namespaced exports
export {
	tabs,
	activeTabId,
	activeTab,
	splitMode,
	preferences,
	recentFiles,
	loading,
	dirtyTabs,
	hasDirtyTabs,
	openFile,
	closeTab,
	forceCloseTab,
	closeAllTabs,
	closeOtherTabs,
	setActiveTab,
	updateContent,
	markSaved,
	reorderTabs,
	setSplitMode,
	updatePreferences,
	resetPreferences,
	getTab,
	getTabByPath,
	nextTab,
	prevTab,
	setLoading,
	// Renamed to avoid conflict
	error as editorError,
	setError as setEditorError,
	updateCursor as updateEditorCursor,
	setAIEditing
} from './editor.svelte';

// AI store
export {
	conversations,
	activeConversationId,
	activeConversation,
	messages,
	tools,
	editSessions,
	activeEditSessions,
	suggestions,
	isStreaming,
	isPanelOpen,
	createConversation,
	setActiveConversation,
	deleteConversation,
	addMessage,
	updateMessage,
	sendMessage,
	registerTool,
	unregisterTool,
	updateConfig,
	togglePanel,
	openPanel,
	closePanel,
	startEditSession,
	updateEditSession,
	completeEditSession,
	resolveEditSession,
	addSuggestion,
	removeSuggestion,
	clearSuggestions,
	updateContext,
	// Renamed to avoid conflicts
	config as aiConfig,
	error as aiError,
	clearError as clearAIError
} from './ai.svelte';

// Plugin store
export {
	proposals,
	instances,
	activeInstances,
	commands,
	panels,
	connected,
	loadingProposals,
	loadingInstance,
	draftProposals,
	reviewingProposals,
	deployedProposals,
	connect,
	fetchProposals,
	createProposal,
	submitProposal,
	loadPlugin,
	unloadPlugin,
	registerCommand,
	registerPanel,
	executeCommand,
	getProposal,
	getInstance,
	clearError as clearPluginError,
	// Renamed to avoid conflicts
	error as pluginError,
	disconnect as disconnectPlugins,
	onEvent as onPluginEvent
} from './plugin.svelte';

// Collaboration store
export {
	status,
	synced,
	users,
	cursors,
	awareness,
	aiSessions,
	activeAISessions,
	pendingChanges,
	snapshots,
	localUser,
	isConnected,
	otherUsers,
	initialize,
	setStatus,
	setSynced,
	addUser,
	removeUser,
	updateAwareness,
	setLocalCursor,
	setLocalAwareness,
	startAISession,
	updateAISession,
	setAITask,
	proposeAIChange,
	reviewAIChange,
	completeAISession,
	cancelAISession,
	createSnapshot,
	getDocumentSnapshots,
	reset,
	getUserColor,
	// Renamed to avoid conflicts
	config as collabConfig,
	error as collabError,
	updateCursor as updateCollabCursor,
	disconnect as disconnectCollab,
	onEvent as onCollabEvent
} from './collaboration.svelte';

// Layout store - no conflicts
export * from './layout.svelte';

// VFS store
export {
	workspace,
	workspaceLoading,
	files,
	fileTree,
	locks,
	dirtyFiles,
	activeTransactions,
	syncing,
	getWorkspace,
	getWorkspaceLoading,
	getFiles,
	getFileTree,
	getFile,
	getLocks,
	getLock,
	getLockStatus,
	isLocked,
	isLockedByMe,
	isLockedByOther,
	getMyLocks,
	getOtherLocks,
	getDirtyFiles,
	isDirty,
	getActiveTransactions,
	getTransactionHistory,
	getSyncing,
	getVersion,
	getReconnectAttempts,
	getLockedFiles,
	getMyLockedFiles,
	getDirectories,
	getFilesInDirectory,
	initialize as initializeVFS,
	loadWorkspace,
	updateFileInfo,
	removeFileInfo,
	markDirty,
	markClean,
	setFiles,
	setLock,
	removeLock,
	setLockStatus,
	setLocks,
	acquireLock,
	releaseLock,
	releaseAllMyLocks,
	startTransaction,
	completeTransaction,
	setSyncing,
	// Renamed to avoid conflicts
	connected as vfsConnected,
	error as vfsError,
	clearError as clearVFSError,
	connect as connectVFS,
	disconnect as disconnectVFS,
	onEvent as onVFSEvent,
	reset as resetVFS
} from './vfs.svelte';

// Agents store
export {
	agents,
	onlineAgents,
	busyAgents,
	events as agentEvents,
	activities,
	cursors as agentCursors,
	selectedAgent,
	filter as agentFilter,
	getAgents,
	getAgent,
	getOnlineAgents,
	getOfflineAgents,
	getBusyAgents,
	getStalledAgents,
	getAgentsByType,
	getAgentsWorkingOnFile,
	getEvents as getAgentEvents,
	getActivities,
	getActivitiesForAgent,
	getRecentActivities,
	getCursors as getAgentCursors,
	getCursor as getAgentCursor,
	getCursorsForFile,
	getSelectedAgent,
	getFilter as getAgentFilter,
	getFilteredAgents,
	getActiveTasksCount,
	getTotalProgress,
	getAgentCount,
	getOnlineCount,
	addAgent,
	removeAgent,
	updateAgent,
	setAgentStatus,
	setAgentTask,
	updateAgentProgress,
	completeAgentTask,
	updateCursor as updateAgentCursor,
	removeCursor as removeAgentCursor,
	clearCursorsForFile,
	addEvent as addAgentEvent,
	onTeamEvent,
	addActivity,
	selectAgent,
	setFilter as setAgentFilter,
	clearActivities,
	clearEvents as clearAgentEvents,
	handleVFSEvent,
	addMockAgents,
	// Renamed to avoid conflicts
	connected as agentsConnected,
	error as agentsError,
	setConnected as setAgentsConnected,
	setError as setAgentsError,
	clearError as clearAgentsError,
	reset as resetAgents
} from './agents.svelte';
